# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
#  pod 'QiscusCoreAPI', :path => '../QiscusCoreAPI/Build'
#  pod 'QiscusCoreAPI', :path => '../../../QiscusCoreAPI/'
  pod 'QiscusRealtime', :git => 'https://github.com/qiscus/QiscusRealtime-iOS', :branch => 'carthage-support'
  pod 'QiscusCore', :git => 'https://github.com/qiscus/QiscusCore-iOS', :branch => 'carthage-support-v3'
  pod 'MultichannelWidget', :path => '../../'

end
