# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
#  pod 'QiscusCoreAPI', :path => '../QiscusCoreAPI/Build'
#  pod 'QiscusCoreAPI', :path => '../../../QiscusCoreAPI/'
  pod 'MultichannelWidget', :path => '../../'

end
